### ISSUE TITLE
Генерация имён полей структуры в верхнем регистре

### ISSUE THREAD

**Issue by kshamiev** [volatiletech/sqlboiler#1238]
SQLBoiler v4.11.0

База данных:

PostgreSQL 13.9 (Ubuntu 13.9-201-yandex.50768.300d2cfeb5) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

Команда генерации:

sqlboiler -c etc/config_sample.yml -p tpsample -o tpsample --add-soft-deletes --tag db,pg --no-tests --wipe psql

**Схема БД**

```
CREATE TABLE public.minio (
	id uuid NOT NULL DEFAULT uuid_generate_v4(), -- ИД
	bucket text NOT NULL, -- папка хранения - тип объекта
	object_id int8 NOT NULL DEFAULT 0, -- файл хранения - ид объекта
	"name" text NOT NULL, -- имя файла
	file_type text NOT NULL, -- тип файла
	file_size int4 NOT NULL DEFAULT 0, -- размер файла
	"label" jsonb NULL, -- дополнительные параметры файла
	user_login text NOT NULL, -- пользователь
	created_at timestamp NOT NULL DEFAULT now(), -- дата и время создания
	is_confirm bool NOT NULL DEFAULT false, -- подтверждение загрузки
	kpp text NULL,
	inn text NULL,
	CONSTRAINT minio_st_pk PRIMARY KEY (id)
);
CREATE INDEX minio_st_bucket_idx ON public.minio USING btree (bucket);
CREATE UNIQUE INDEX minio_st_object_id_idx ON public.minio USING btree (object_id);

COMMENT ON COLUMN public.minio.id IS 'ИД';
COMMENT ON COLUMN public.minio.bucket IS 'папка хранения - тип объекта';
COMMENT ON COLUMN public.minio.object_id IS 'файл хранения - ид объекта';
COMMENT ON COLUMN public.minio."name" IS 'имя файла';
COMMENT ON COLUMN public.minio.file_type IS 'тип файла';
COMMENT ON COLUMN public.minio.file_size IS 'размер файла';
COMMENT ON COLUMN public.minio."label" IS 'дополнительные параметры файла';
COMMENT ON COLUMN public.minio.user_login IS 'пользователь';
COMMENT ON COLUMN public.minio.created_at IS 'дата и время создания';
COMMENT ON COLUMN public.minio.is_confirm IS 'подтверждение загрузки';
```

**Конфигурация**

```
psql:
  user: "postgres"
  pass: "postgres"
  host: "localhost"
  port: 5432
  dbname: "sample"
  sslmode: "disable"

# Boiler
types:
  # require
  - match:
      db_type: uuid
      nullable: true
    replace:
      type: uuid.UUID
    imports:
      third_party:
        - '"github.com/google/uuid"'
  - match:
      db_type: uuid
      nullable: false
    replace:
      type: uuid.UUID
    imports:
      third_party:
        - '"github.com/google/uuid"'
```

Интресует генерация имён в структуре.

...
type Minio struct {
	...
	KPP       null.String `db:"kpp" pg:"kpp,use_zero" boil:"kpp" json:"kpp,omitempty" swaggertype:"string"`
	Inn       null.String `db:"inn" pg:"inn,use_zero" boil:"inn" json:"inn,omitempty" swaggertype:"string"`
	...
}
...

...
KPP
Все буквы заглавные.
Inn
Как обычно.

Также многие другие аббревиатуры.
Какие-то генерируются стандартно ( Title ).
А у других все буквы заглавные ( TITLE ).

Нельзя ли вынести такое поведение генератора имён полей структуры  в конфигурацию.
Чтобы можно было это отключить и генератор не делал имена разными
Либо отключить такое поведение генратора вообще.
Чтобы не генерировал часть полей в верхнем регистре.
...
