### ISSUE TITLE
Struct and function have the same name: News' redeclared in this package

### ISSUE THREAD

**Issue by EugeneTorap** [volatiletech/sqlboiler#1249]
Hi @stephenafamo!
I have the next PG table name: `news`. When I generate sqlboiler models I have the problem with the same struct and function names.
Can we add some suffix `List` for this table names?. For example: func name will be `NewsList` for `news` table.

> Code generated by SQLBoiler 4.14.0

![image](https://user-images.githubusercontent.com/29536522/220086048-d163d01c-a383-44b7-af3e-ea74a2e60cb1.png)

**Comment by stephenafamo** [comment]
What's the duplicate definition?

Can you show where it is redeclared?

**Comment by EugeneTorap** [comment]
@stephenafamo here
![image](https://user-images.githubusercontent.com/29536522/220186394-66e180f1-3b80-4bf0-9064-f9348139b7c4.png)

**Comment by EugeneTorap** [comment]
@stephenafamo Can you fix the bug?

**Comment by stephenafamo** [comment]
It's not a bug really. The thing is, SQLBoiler cannot figure out the singular/plural form of the model. You have to configure this manually through the [aliases](https://github.com/volatiletech/sqlboiler#aliases). For example:

```toml
[aliases.tables.news]
up_plural     = "NewsList"
up_singular   = "News"
down_plural   = "newsList"
down_singular = "news"
```
