### ISSUE TITLE
Replace autogenerated enum

### ISSUE THREAD

**Issue by MJacred** [volatiletech/sqlboiler#1355]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.14.2

### What is your database and version (eg. Postgresql 10)

MariaDB v10.11.2

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
CREATE TABLE IF NOT EXISTS TableA (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,

  my_enum ENUM('A', 'B', 'C'),

  PRIMARY KEY (id)
);
```

sqlboiler.toml
```toml
add-enum-types = true

[[types]]
  [[types.match]]
    name = "my_enum"
    # tables = ["TableA"]

  [[types.replace]]
    type = "models_types.MyEnum"
  
  [[types.imports]]
    third_party = ['"test.com/test/models_types"']
```

test/test.go
```golang
package models_types

import "github.com/friendsofgo/errors"

type MyEnum string

// Enum values for MyEnum
const (
	MyEnumA MyEnum = "A"
	MyEnumB MyEnum = "B"
	MyEnumC MyEnum = "C"
)

func AllMyEnum() []MyEnum {
	return []MyEnum{
		MyEnumA,
		MyEnumB,
		MyEnumC,
	}
}

func (e MyEnum) IsValid() error {
	switch e {
	case MyEnumA, MyEnumB, MyEnumC:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e MyEnum) String() string {
	return string(e)
}
```

### Further information. What did you do, what did you expect?

https://github.com/volatiletech/sqlboiler?tab=readme-ov-file#types suggests, you can replace a type used in the autogenerated code.  
This seems to not work with enums. At least the setup I provided in the previous chapter had no effect.

**Comment by stephenafamo** [comment]
What does the generated model look like?

**Comment by MJacred** [comment]
@stephenafamo: I updated the example and added the generated model

**Comment by stephenafamo** [comment]
The issue is your config. You're missing something with the TOML syntax and you're using double square brackets where single square brackets should be used.

```toml
add-enum-types = true

[[types]]
  [types.match]
    name = "my_enum"
    # tables = ["TableA"]

  [types.replace]
    type = "models_types.MyEnumOverride"
  
  [types.imports]
    third_party = ['"test.com/test/models_types"']
```


> It would be a cleaner experience to replace their types with 1 self-created one…

Side note, you can just replace one of the enums with the second auto generated one so that you don't have to maintain the values yourself 🤷🏾‍♂️
