### ISSUE TITLE
Generation redeclares variables & aliases not applying

### ISSUE THREAD

**Issue by kelzenberg** [volatiletech/sqlboiler#1401]
Generated model files redeclare variables from other generated model files because the table name finishes with the word "column". Then tests will fail with:
```
models/BmElementColumn.go:524:6: BmElementColumns redeclared in this block
	models/BmElement.go:172:5: other declaration of BmElementColumns
```
More info below.

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.16.2

### What is your database and version (eg. Postgresql 10)
Microsoft SQL Server 16.0.1000

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler mssql`
`go test ./models`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
create table BmElement
(
    UUID  uniqueidentifier not null primary key,
    -- other attributes
)

create table BmElementColumn
(
    UUID  uniqueidentifier not null primary key,
    -- other attributes
)
```

#### `sqlboiler.toml`
```toml
pkgname = "models"
output = "models"
wipe = true
add-enum-types = true

[mssql]
dbname = "..."
host = "..."
port = 0
user = "..."
pass = "..."
schema = "dbo"
sslmode = "disable"
```

Among other tables in the mssql database, I have two tables `BmElement` and `BmElementColumn` (and I can't edit the schema).
- I ran `sqlboiler mssql`
- It created go files in the models folder for all tables successfully
- It generated the `var BmElementColumns = struct{}` as static constants for column names for the BmElement table
- It generated the `func BmElementColumns(mods ...qm.QueryMod) bmElementColumnQuery {}` function to retrieve all records using an executor for the BmElementColumn table
- Go complaints (rightfully) about redeclared variables

As you can see the table naming interferes with the generated suffixes of table functions and variables. I tried to use aliases and inflection (see comment below).

**Comment by kelzenberg** [comment]
I tried aliases the problematic table but I see no change in the generated models.
```toml
[aliases.tables.BmElementColumn]
up_plural = "BmElementColumnsA"
up_singular = "BmElementColumn"
down_plural = "bmElementColumnsA"
down_singular = "bmElementColumn"
```

Then I tried changing the way plural wording is created, also no change.
```toml
[inflections.plural_exact]
column = "columnsAll"
```

What am I missing here?

**Comment by kelzenberg** [comment]
Adding this to the config file:
```toml
[aliases.tables.BmElementColumn]
up_plural = "BmElementColumnsFoo"
up_singular = "BmElementColumnFoo"
down_plural = "bmElementColumnsFoo"
down_singular = "bmElementColumnFoo"
```
Lists this in the JSON debug output:
```json
"config": {
  "aliases": {
    "tables": {
        "BmElementColumn": {
          "up_plural": "BmElementColumns",
          "up_singular": "BmElementColumn",
          "down_plural": "bmElementColumns",
          "down_singular": "bmElementColumn",
          "columns": [...],
        }
        ...
        "bmelementcolumn": {
          "up_plural": "BmElementColumnsFoo",
          "up_singular": "BmElementColumnFoo",
          "down_plural": "bmElementColumnsFoo",
          "down_singular": "bmElementColumnFoo"
        }
    }
  }
}
```

Clearly the case-sensitivity is the culprit here.
