### ISSUE TITLE
Inconsistent Foreign Key Order in Generated Code When Using Key-Value Syntax in sqlboiler.toml

### ISSUE THREAD

**Issue by garigari-kun** [volatiletech/sqlboiler#1445]
When using the key-value syntax (`[foreign_keys.name]`) in the `sqlboiler.toml` configuration file, the order of foreign keys in the generated code appears to be inconsistent. 

For example, given the following configuration using the key-value syntax:

```sql
CREATE TABLE `test_item`
(
  `id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `test_category_id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `test_group_id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `test_provider_id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `test_category`
(
  `id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `test_group`
(
  `id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `test_provider`
(
  `id` varchar(16) COLLATE utf8mb4_general_ci NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

```toml
[foreign_keys.test_item_ibfk_1]
  table = "test_item"
  column = "test_category_id"
  foreign_table = "test_category"
  foreign_column = "id"

[foreign_keys.test_item_ibfk_2]
  table = "test_item"
  column = "test_group_id"
  foreign_table = "test_group"
  foreign_column = "id"

[foreign_keys.test_item_ibfk_3]
  table = "test_item"
  column = "test_provider_id"
  foreign_table = "test_provider"
  foreign_column = "id"
```

The generated code does not always maintain the order of the foreign keys as defined in the configuration file. This issue does not occur when using the array syntax ([[foreign_keys]]), which seems to preserve the order.

My question is that 
- Since sqlboiler is in maintenance mode, would a pull request addressing this issue be considered for inclusion?
- Alternatively, should users rely on the array syntax ([[foreign_keys]]) to ensure the order of foreign keys is preserved?

Thank you for maintaining this project and for considering this issue.
