### ISSUE TITLE
Performance regression in code generation after upgrading to v4.19.0

### ISSUE THREAD

**Issue by RikiyaFujii** [volatiletech/sqlboiler#1449]
After upgrading to `sqlboiler` v4.19.0, I've noticed that running the following command takes significantly longer than in previous versions:

```sh
$ sqlboiler psql -c ./sqlboiler.toml
```

I’ve reviewed the release notes, but I wasn’t able to find any explanation for this behavior.

Here is my sqlboiler.toml configuration:

```toml
no-tests = true
add-enum-types = true

[psql]
  dbname  = "postgres"
  host    = "localhost"
  port    = 5432
  user    = "postgres"
  pass    = "password"
  sslmode = "disable"
```

I’d really appreciate it if you could investigate this issue, or let me know if there are any known changes that might affect generation performance in v4.19.0.

Thank you.
