### ISSUE TITLE
Type assertion error when use yaml as config file

### ISSUE THREAD

**Issue by ch3rub1m** [volatiletech/sqlboiler#439]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.1.0

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
```
panic: interface conversion: interface {} is map[interface {}]interface {}, not map[string]interface {}
```

### Further information. What did you do, what did you expect?
For example, It's my yaml file:
```
mysql:
  dbname: auth
  host: localhost
  sslmode: "false"
  user: root
  whitelist:
  - users
aliases:
  tables:
  - name: users
    columns:
    - name: created_at
      alias: CreateTime
```
The viper will infer that `aliases.tables` and `aliases.tables.columns` are `[]map[interface{}]interface{}` and it's different with toml.

However, in `boilingcore/config.go` there are many hardcode about type assertions, like `something.(map[string]interface{})`. It will cause crash if use yaml as config file.
