### ISSUE TITLE
"output" option not working in sqlboiler.toml 

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#443]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.1.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql`

### Further information. What did you do, what did you expect?
My models are in `./cmd/models/`, so I put this on my sqlboiler.toml as shown below. But I get them generated at `./models/` unless I use `sqlboiler --output cmd/models psql` in which case I get the models where I want.

```toml
[psql]
dbname = 'mydb'
user = 'iamuser'
pass = 'thisispass'
host = '127.0.0.1'
port = 5432
output = 'cmd/models' #  <-------- This doesn't work
no-hook = true
no-tests = true
sslmode = 'disable'
```

**Comment by andradei** [comment]
Thank you. Reading the README again makes sense. One suggestion would be to have the table of configs and the examples of driver-specific code combined so it makes it even more obvious what the config file should look like:

```toml

pkgname = "models"
output = "models"
tag = []
debug = false
add-global-variants = false
add-panic-variants = false
no-context = false
no-hooks = false
no-tests = false
no-auto-timestamps = false
no-rows-affected = false

[psql]
dbname = "dbname"
host = "localhost"
port = 5432
user = "dbusername"
pass = "dbpassword"
schema = "myschema"
blacklist = ["migrations", "other"]

[mysql]
dbname = "dbname"
host = "localhost"
port = 3306
user = "dbusername"
pass = "dbpassword"
sslmode = "false"

[mssql]
dbname = "dbname"
host = "localhost"
port = 1433
user = "dbusername"
pass = "dbpassword"
sslmode = "disable"
schema = "notdbo"
```
