### ISSUE TITLE
provide uuid for binary(16)

### ISSUE THREAD

**Issue by lelvisl** [volatiletech/sqlboiler#529]
How to provide uuid (bd_type: binary(16))?

I'm trying this configuration:
```yaml
pkgname: dbmodel
output: dbmodel

mysql:
  dbname: DEV
  host: localhost
  port: 3306
  user: user
  pass: pass
  schema: DEV
  sslmode: false
  blacklist: 
  - imp
  types:
  - match:
      db_type: binary
      length: 16
    replace:
      type: uuid.UUID
    imports:
      third_party:
        - '"github.com/satori/go.uuid"'
        # - '"github.com/google/uuid"'
```

In result:
```bash
$ sqlboiler mysql
Error: unable to initialize tables: unable to fetch table data: failed to json-ify driver configuration: json: unsupported type: map[interface {}]interface {}

```
