### ISSUE TITLE
sqlboiler.json is not liked, but sqlboiler.toml is liked

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#676]
I got this error:

```
panic: interface conversion: interface {} is map[string]interface {}, not []interface {}

goroutine 1 [running]:
github.com/volatiletech/sqlboiler/boilingcore.ConvertTypeReplace(0x944a20, 0xc0001b2060, 0x5, 0x944a20, 0xc0001b2060)
        /home/oleg/go/src/github.com/volatiletech/sqlboiler/boilingcore/config.go:180 +0x4c5
main.preRun(0xc000194b00, 0xc0000d1970, 0x1, 0x1, 0x0, 0x0)
        /home/oleg/go/src/github.com/volatiletech/sqlboiler/main.go:183 +0x5c5
github.com/spf13/cobra.(*Command).execute(0xc000194b00, 0xc0000de030, 0x1, 0x1, 0xc000194b00, 0xc0000de030)
        /home/oleg/go/src/github.com/spf13/cobra/command.go:829 +0x514
github.com/spf13/cobra.(*Command).ExecuteC(0xc000194b00, 0xc0000beac0, 0x2, 0x2)
        /home/oleg/go/src/github.com/spf13/cobra/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/oleg/go/src/github.com/spf13/cobra/command.go:885
main.main()
        /home/oleg/go/src/github.com/volatiletech/sqlboiler/main.go:118 +0xcff

```

I was using this toml config:

```toml
pkgname = "model"
output = "v1/model"

[psql]
dbname = "creatorpay"
host = "pg.channelmeter.com"
user = "postgres"
blacklist = []

[[types]]
    [types.match]
        type = "types.Decimal"
    [types.replace]
        type = "apd.Decimal"
    [types.imports]
        third_party = ['"github.com/cockroachdb/apd"']

[[types]]
    [types.match]
        db_type = "uuid"
        nullable = false
    [types.replace]
        type = "uuid.UUID"
    [types.imports]
        third_party = ['"github.com/google/uuid"']
```

I converted it to JSON:

```json
{
  "pkgname": "model",
  "output": "v1/model",
  "psql": {
    "dbname": "creatorpay",
    "host": "pg.channelmeter.com",
    "user": "postgres",
    "blacklist": []
  },
  "types": {
    "match": {
      "type": "types.Decimal",
      "db_type": "uuid",
      "nullable": false
    },
    "replace": {
      "type": "uuid.UUID"
    },
    "imports": {
      "third_party": [
        "github.com/google/uuid"
      ]
    }
  }
}
```

but when I ran:

```
sqlboiler psql
```

I got the above error..I assume it's because it wasn't handling JSON well but idk.

Suggestion - in the docs, explicitly include the configuation file:

```
sqlboiler -c sqlboiler.json  psql
```

that is much more sane, it's better for the docs.
