### ISSUE TITLE
The configuration file written in README.md does not work properly

### ISSUE THREAD

**Issue by dqn** [volatiletech/sqlboiler#765]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.7.1

### What is your database and version (eg. Postgresql 10)

PostgreSQL 12.3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler psql`

### Further information. What did you do, what did you expect?

[This configuration file](https://github.com/volatiletech/sqlboiler#full-example) does not work properly. But, it worked properly with `no-tests` instead of `no_tests`.

**Comment by dqn** [comment]
If this is a bug, need to unify all options to kebab-case or fix snake_case options to be equivalent to kebab-case.

The viper provides `SetEnvKeyReplacer`, but this doesn't seem to work for configuration file.

**Comment by dqn** [comment]
Resolved by using SQLBoiler v4.1.2.

**Comment by dqn** [comment]
Sorry, it wasn't resolved

**Comment by dqn** [comment]
FYI: my `sqlboiler.toml`

```toml
output   = "models"
wipe     = true
no_tests = true # Not work.

[psql]
  dbname  = "app"
  host    = "localhost"
  port    = 5432
  user    = "admin"
  pass    = "admin"
  schema  = "public"
  sslmode = "disable"
```
