### ISSUE TITLE
Trouble Running SQLBoiler

### ISSUE THREAD

**Issue by dtrinh100** [volatiletech/sqlboiler#778]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.1.2

### What is your database and version (eg. Postgresql 10)

Postgres 12.3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler psql

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

Doesn't appear to be a schema issue, but I can provide if needed. 

### Further information. What did you do, what did you expect?

I am not sure if I followed the installation instructions properly. I did a go get on sqlboiler and the driver outside of my application folder, so this might be a possible problem.

I run my Postgres database within a database container via docker-compose. The configuration looks like this:

```
postgres:
    container_name: postgres
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
```

My sqlboiler.toml looks like this:

```
output   = "my_models"
wipe     = true


[psql]
  dbname = "postgres"
  host   = "postgres"
  port   = 5432
  user   = "postgres"
  pass   = "supersecret"
  schema = "public"
  blacklist = ["schema_migrations"]

```

Error:

```
unable to get table names: dial tcp: lookup postgres: no such host
Error: unable to initialize tables: unable to fetch table data: driver (/Users/username/go/bin/sqlboiler-psql) exited non-zero: exit status 1
```

I am running the sqlboiler tool locally, not inside of the docker container.
