### ISSUE TITLE
models.TableNames does not match alias definitions

### ISSUE THREAD

**Issue by mgrubb** [volatiletech/sqlboiler#813]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)
Postgresql 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql (I have the following in my sqlboiler.toml file)
```toml
[aliases.tables.ab_envs]
up_plural = "ABEnvs"
up_singular = "ABEnv"
down_plural = "abEnvs"
down_singular = "abEnv"
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE IF NOT EXISTS ab_envs (id serial PRIMARY KEY, name varchar(25) NOT NULL UNIQUE);
```
### Further information. What did you do, what did you expect?
I ran sqlboiler, no errors, and everything except the models.TablesNames use the alias as defined.
models.TableNames contains AbEnvs instead of ABEnvs.  I would expect model.TableNames to be consistent with the alias definitions.
