### ISSUE TITLE
m2m join table not appearing in generated results for relationships

### ISSUE THREAD

**Issue by erikh** [volatiletech/sqlboiler#948]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.5.0

### What is your database and version (eg. Postgresql 10)

12.6

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

`sqlboiler psql`. TOML:

```toml
output  = "models"
pkgname = "models"
wipe    = true

[psql]
dbname    = "tinyci"
host      = "localhost"
port      = 5432
user      = "tinyci"
pass      = "tinyci"
blacklist = ["gorp_migrations"]
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

Project is sqlboiler branch of https://github.com/erikh/ci-agents, fwiw, in the `db` dir.

https://gist.github.com/9ffb80b617bf94011c99d8f14f8d1310 is the dump

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

https://gist.github.com/erikh/0fa9efb1629fe08ba15a5828b961bc43

### Further information. What did you do, what did you expect?

I'm currently porting from gorm 1.x; the m2m table for `subscriptions` generates no members on repositories or users, despite having a CPK for both and a foreign key into both tables. Not sure what to do here tbh, or if there's a bug. I read the docs but it seems like this should work from what I read. Sorry if I misread something and wasted your time.
